---
variables:
  MAVEN_CLI_OPTS: '--batch-mode'
  MAVEN_OPTS: '-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository'

cache:
  paths:
    - .m2/repository/

.default-job-settings:
  tags:
    - maven
    - java
    - docker

stages:
  - build
  - build-docker
  - deploy

build:
  extends: .default-job-settings
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install -U -Prelease
    - mv target/*.zip .
  artifacts:
    name: insights-api-$CI_COMMIT_REF_SLUG
    paths:
      - '*.zip'

build-docker:
  when: manual
  extends: .default-job-settings
  stage: build-docker
  script:
    - mvn $MAVEN_CLI_OPTS clean install jib:build -U -Prelease
    - mv target/*.zip .
  artifacts:
    name: insights-api-$CI_COMMIT_REF_SLUG
    paths:
      - '*.zip'

deploy-test:
  tags:
    - kontur
    - ansible
  stage: deploy
  script: >
    ansible-playbook -vD -e "version=$CI_COMMIT_REF_SLUG-$CI_PIPELINE_IID
    path_to_dist=$(find $CI_PROJECT_DIR -maxdepth 1 -name \*.zip -print -quit)"
    --limit=sonic_insights_api ansible/deploy.yml
  environment:
    name: TEST
    url: 'https://test-apps.konturlabs.com/insights/'
  when: manual
  dependencies:
    - build

deploy-dev:
  tags:
    - kontur
    - ansible
  stage: deploy
  script: >
    ansible-playbook -vD -e "version=$CI_COMMIT_REF_SLUG-$CI_PIPELINE_IID
    path_to_dist=$(find $CI_PROJECT_DIR -maxdepth 1 -name \*.zip -print -quit)"
    --limit=zigzag_insights_api ansible/deploy.yml
  environment:
    name: DEV
    url: 'https://test-apps02.konturlabs.com/insights/'
  when: manual
  dependencies:
    - build

deploy-prod:
  tags:
    - kontur
    - ansible
  stage: deploy
  script: >
    ansible-playbook -vD -e "version=$CI_COMMIT_REF_SLUG-$CI_PIPELINE_IID
    path_to_dist=$(find $CI_PROJECT_DIR -maxdepth 1 -name \*.zip -print -quit)"
    --limit=lima_insights_api ansible/deploy.yml
  environment:
    name: PROD
    url: 'https://apps.kontur.io/insights/'
  only:
    - /^release-.*$/
  when: manual
  dependencies:
    - build
