server:
  servlet:
    contextPath: /insights-api
  port: 8625
  shutdown: graceful

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: password
    hikari:
      register-mbeans: true
      pool-name: HikariPool-1
      connection-timeout: 60000
      validation-timeout: 1000
      maximum-pool-size: 10
  jdbc:
    template:
      query-timeout: 300
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml
  lifecycle:
    timeout-per-shutdown-phase: 310s

graphql:
  servlet:
    corsEnabled: false
    tracing-enabled: false
    actuator-metrics: true

management:
  metrics:
    export:
      simple:
        enabled: false
  health:
    db:
      enabled: true
    ping:
      enabled: false
    diskspace:
      enabled: false
    refresh:
      enabled: false
  endpoint:
    health:
      status:
        http-mapping:
          down: 200
      cache:
        time-to-live: 10s
      show-details: always
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

retry:
  functionRequest:
    delay: 1000
    multiplier: 2

bivatiateMatrix:
  highCorrelationLevel: 0.75

cache:
  maximumSize: 10000
  functions: true
  humanitarian-impact: true
  osm-quality: true
  population: true
  thermal-spot: true
  urban-core: true
  correlation-rate: true
  advanced-analytics: true