server:
  servlet:
    contextPath: /insights-api
  port: 8625
  shutdown: graceful

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: password
    hikari:
      register-mbeans: true
      pool-name: HikariPool-1
      connection-timeout: 60000
      validation-timeout: 1000
      maximum-pool-size: 10
  jdbc:
    template:
      query-timeout: 300
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml
  lifecycle:
    timeout-per-shutdown-phase: 310s
  cache:
    type: redis
    cache-names: urban-core, thermal-spot, population, osm-quality, humanitarian-impact, functions, correlation-rate-all,
      correlation-rate-num-den, correlation-rate-polygon, correlation-rate-num-not-empty-layers, advanced-analytics-all,
      advanced-analytics
    redis:
      time-to-live: 86400
  redis:
    host: localhost
    port: 6379

graphql:
  servlet:
    corsEnabled: false
    tracing-enabled: false
    actuator-metrics: true
    async:
      timeout: 600s

management:
  metrics:
    export:
      simple:
        enabled: false
  health:
    db:
      enabled: true
    ping:
      enabled: false
    diskspace:
      enabled: false
    refresh:
      enabled: false
  endpoint:
    health:
      status:
        http-mapping:
          down: 200
      cache:
        time-to-live: 10s
      show-details: always
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /
      path-mapping:
        prometheus: metrics

bivatiateMatrix:
  highCorrelationLevel: 0.75

cache:
  functions: true
  humanitarian-impact: true
  osm-quality: true
  population: true
  thermal-spot: true
  urban-core: true
  correlation-rate: true
  advanced-analytics: true

graphql-request:
  parser-options:
    max-tokens: 0x7fffffff #Integer.MAX_VALUE