server:
  servlet:
    contextPath: /insights-api
  port: 8625

spring:
  datasource:
    platform: postgres
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: password
    hikari:
      register-mbeans: true
      pool-name: HikariPool-1
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml

graphql:
  servlet:
    corsEnabled: false