server:
  servlet:
    contextPath: /insights-api
  port: 8625

spring:
  main:
    lazy-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: password
    hikari:
      register-mbeans: true
      pool-name: HikariPool-1
      connection-timeout: 60000
      validation-timeout: 1000
      maximum-pool-size: 10
  jdbc:
    template:
      query-timeout: 1800
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml

springdoc:
  packages-to-scan: io.kontur.insightsapi.controller

graphql:
  servlet:
    corsEnabled: false
    tracing-enabled: false
    actuator-metrics: true
    async:
      timeout: 1800s
  tools:
    schema-location-pattern: graphql/*.graphqls

management:
  metrics:
    export:
      simple:
        enabled: false
  health:
    ping:
      enabled: false
    diskspace:
      enabled: false
    refresh:
      enabled: false
  endpoint:
    health:
      status:
        http-mapping:
          down: 200
      cache:
        time-to-live: 10s
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

bivatiateMatrix:
  highCorrelationLevel: 0.75

cache:
  maximumSize: 10000
  functions: true
  humanitarian-impact: true
  osm-quality: true
  population: true
  thermal-spot: true
  urban-core: true
  correlation-rate: true
  advanced-analytics: true

graphql-request:
  parser-options:
    max-tokens: 0x7fffffff #Integer.MAX_VALUE