{{ if ne .Values.envName "local" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.envName }}-insights-api
  namespace: {{ .Values.envName }}-insights-api
  labels:
    app.kubernetes.io/name: insights-api
    app.kubernetes.io/instance: {{ .Values.envName }}-insights-api
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - interval: 30s
      port: main
      path: /metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: insights-api
      app.kubernetes.io/instance: {{ .Values.envName }}-insights-api
      #don't add app.kubernetes.io/version
      app.kubernetes.io/managed-by: "Helm"
      stage: {{ .Values.envName }}
---
{{ end }}