---
apiVersion: v1
kind: Service
metadata:
  name: insights-api-{{ .Values.envName }}
  namespace: sandbox-isemichastnov
  labels:
    app.kubernetes.io/name: insights-api
    app.kubernetes.io/instance: insights-api-{{ .Values.envName }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: insights-api
    app.kubernetes.io/instance: insights-api-{{ .Values.envName }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  ports:
    - port: 8625
      targetPort: 8625
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: insights-api-{{ .Values.envName }}-database
  namespace: sandbox-isemichastnov
  labels:
    app.kubernetes.io/name: insights-api
    app.kubernetes.io/instance: insights-api-{{ .Values.envName }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.databaseHost }}
  #  externalName: docker.for.mac.host.internal #todo for local dev
  ports:
    - port: 5432
---
