apiVersion: v1
kind: ConfigMap
metadata:
  name: insights-api-dev
  namespace: sandbox-isemichastnov
  labels:
    app.kubernetes.io/name: insights-api
    app.kubernetes.io/instance: insights-api-dev
    stage: dev
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: 'jdbc:postgresql://insights-api-dev-database:5432/insights-api'
  SPRING_DATASOURCE_USERNAME: insights-api
  #TODO do not use uppercase var names for hikari properties otherwise startup fails with smth like 'The configuration of the pool is sealed once started.'
  spring.datasource.hikari.connection-timeout: '600000'
  spring.datasource.hikari.maximum-pool-size: '20'
  SPRING_JDBC_TEMPLATE_QUERY_TIMEOUT: '600'
---
#TODO: create manually
#apiVersion: v1
#kind: Secret
#metadata:
#  name: insights-api-dev
#  namespace: sandbox-isemichastnov
#  labels:
#    app.kubernetes.io/name: insights-api
#    app.kubernetes.io/instance: insights-api-dev
#    app.kubernetes.io/version: insights-api-dev
#data:
#  SPRING_DATASOURCE_PASSWORD: base64 encoded password
---