--- # Time-stamp: <2022-09-17 20:19:59>

name: 01 Building with Maven

'on':
  - push
  - fork

jobs:
  helper:
    uses: ./.github/workflows/migration-helper01.yml
  build:
    runs-on: ubuntu-latest
    needs: helper
    # strategy:
    #   matrix:
    #     os:
    #       - ubuntu-latest
    # runs-on: '${{ matrix.os }}'
    steps:

      - uses: actions/checkout@v3

      - name: Extracting metadata from a cloned repository
        id: get-cloned
        run: |-
          echo "::set-output name=SHA::$(git log -1 --format='%h')"

      - uses: actions/setup-java@v3
        with:
          java-version: 16
          distribution: corretto
          cache: maven

      - name: Building with Maven
        env:
          MAVEN_CLI_OPTS: '--batch-mode'
          NEXUS_DEPLOYER: ${{ secrets.NEXUS_DEPLOYER }}
          NEXUS_DEPLOYER_PASS: ${{ secrets.NEXUS_DEPLOYER_PASS }}
          IMAGE_TAG: ${{ format('{0}.{1}.{2}', github.ref_name, steps.get-cloned.outputs.SHA, github.run_attempt) }}
        run: |-
          set -e

          # sanitize IMAGE_TAG for jib-compatible docker tagging
          IMAGE_TAG="$(echo "$IMAGE_TAG" | tr '/' '-')"
          wget -q https://kontur-github-runners.s3.eu-central-1.amazonaws.com/public_resources/projects/common/2022091500.tar.xz && tar -C "$HOME" -xf 2022091500.tar.xz && rm 2022091500.tar.xz

          echo '${{ secrets.NEXUS_DEPLOYER_PASS }}' | docker login nexus.kontur.io:8084 -u '${{ secrets.NEXUS_DEPLOYER }}' --password-stdin
          echo '${{ secrets.NEXUS_DEPLOYER_PASS }}' | docker login nexus.kontur.io:8085 -u '${{ secrets.NEXUS_DEPLOYER }}' --password-stdin

          IMAGE_TAG="$IMAGE_TAG" mvn $MAVEN_CLI_OPTS clean install jib:build -U
          echo "<h3>Docker image tag</h3> $IMAGE_TAG <br><br>" >> $GITHUB_STEP_SUMMARY
